### PR TITLE
fix: migrate from k8s.gcr.io to registry.k8s.io

### PR DESCRIPTION
**Pull request by CIPHERTron**
This fix is a part of an umbrella issue https://github.com/kubernetes/k8s.io/issues/4780

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
@PhilipCattanach can you PTAL?

**Comment by PhilipCattanach** [comment]
@carlosthe19916 - Could you review this PR please?

**Comment by carlosthe19916** [comment]
@CIPHERTron @ahmedwaleedmalik @PhilipCattanach I don't see anything wrong in this PR since it only changes the name of the registry from which the container image is being pulled. However, the file [Dockerfile.init](Dockerfile.init) has been fully rewritten in the `main`  branch. Is this PR still valid given the fact that the file Dockerfile.init has been modified very recently?

**Comment by ahmedwaleedmalik** [comment]
@carlosthe19916 @CIPHERTron  I think we can close this PR.

**Pull request closed without merging**
